
# Efinity Interface Designer SDC
# Version: 2020.1.140.1.5
# Date: 2020-08-01 23:42

# Copyright (C) 2017 - 2020 Efinix Inc. All rights reserved.

# Device: T8F81
# Project: soc_opalSoc
# Timing Model: C2 (final)

# PLL Constraints
#################
create_clock -period 50.09 [get_ports {io_systemClk}]

# GPIO Constraints
####################
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {io_asyncReset}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {io_asyncReset}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_uart_0_io_rxd}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_uart_0_io_rxd}]
set_output_delay -clock io_systemClk -max -3.903 [get_ports {system_spi_1_io_ss}]
set_output_delay -clock io_systemClk -min -1.615 [get_ports {system_spi_1_io_ss}]
set_output_delay -clock io_systemClk -max -3.903 [get_ports {system_spi_1_io_sclk_write}]
set_output_delay -clock io_systemClk -min -1.615 [get_ports {system_spi_1_io_sclk_write}]
set_output_delay -clock io_systemClk -max -3.903 [get_ports {system_spi_0_io_sclk_write}]
set_output_delay -clock io_systemClk -min -1.615 [get_ports {system_spi_0_io_sclk_write}]
set_output_delay -clock io_systemClk -max -3.903 [get_ports {system_spi_0_io_ss}]
set_output_delay -clock io_systemClk -min -1.615 [get_ports {system_spi_0_io_ss}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_uart_0_io_txd}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_uart_0_io_txd}]
set_input_delay -clock io_systemClk -max 5.958 [get_ports {system_spi_1_io_data_0_read}]
set_input_delay -clock io_systemClk -min 2.128 [get_ports {system_spi_1_io_data_0_read}]
set_output_delay -clock io_systemClk -max -3.903 [get_ports {system_spi_1_io_data_0_write}]
set_output_delay -clock io_systemClk -min -1.615 [get_ports {system_spi_1_io_data_0_write}]
set_output_delay -clock io_systemClk -max -3.913 [get_ports {system_spi_1_io_data_0_writeEnable}]
set_output_delay -clock io_systemClk -min -1.612 [get_ports {system_spi_1_io_data_0_writeEnable}]
set_input_delay -clock io_systemClk -max 5.958 [get_ports {system_spi_1_io_data_1_read}]
set_input_delay -clock io_systemClk -min 2.128 [get_ports {system_spi_1_io_data_1_read}]
set_output_delay -clock io_systemClk -max -3.903 [get_ports {system_spi_1_io_data_1_write}]
set_output_delay -clock io_systemClk -min -1.615 [get_ports {system_spi_1_io_data_1_write}]
set_output_delay -clock io_systemClk -max -3.913 [get_ports {system_spi_1_io_data_1_writeEnable}]
set_output_delay -clock io_systemClk -min -1.612 [get_ports {system_spi_1_io_data_1_writeEnable}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_read[0]}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_read[0]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_write[0]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_write[0]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_writeEnable[0]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_writeEnable[0]}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_read[1]}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_read[1]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_write[1]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_write[1]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_writeEnable[1]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_writeEnable[1]}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_read[2]}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_read[2]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_write[2]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_write[2]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_writeEnable[2]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_writeEnable[2]}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_read[3]}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_read[3]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_write[3]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_write[3]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_writeEnable[3]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_writeEnable[3]}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_read[4]}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_read[4]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_write[4]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_write[4]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_writeEnable[4]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_writeEnable[4]}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_read[5]}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_read[5]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_write[5]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_write[5]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_writeEnable[5]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_writeEnable[5]}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_read[6]}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_read[6]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_write[6]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_write[6]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_writeEnable[6]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_writeEnable[6]}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_read[7]}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_read[7]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_write[7]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_write[7]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_writeEnable[7]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_writeEnable[7]}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_read[8]}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_read[8]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_write[8]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_write[8]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_writeEnable[8]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_writeEnable[8]}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_read[9]}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_read[9]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_write[9]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_write[9]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_writeEnable[9]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_writeEnable[9]}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_read[10]}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_read[10]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_write[10]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_write[10]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_writeEnable[10]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_writeEnable[10]}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_read[11]}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_read[11]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_write[11]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_write[11]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_writeEnable[11]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_writeEnable[11]}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_read[12]}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_read[12]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_write[12]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_write[12]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_writeEnable[12]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_writeEnable[12]}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_read[13]}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_read[13]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_write[13]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_write[13]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_writeEnable[13]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_writeEnable[13]}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_read[14]}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_read[14]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_write[14]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_write[14]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_writeEnable[14]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_writeEnable[14]}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_read[15]}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_read[15]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_write[15]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_write[15]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_gpio_0_io_writeEnable[15]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_gpio_0_io_writeEnable[15]}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_i2c_0_io_scl_read}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_i2c_0_io_scl_read}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_i2c_0_io_scl_write}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_i2c_0_io_scl_write}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_i2c_0_io_scl_writeEnable}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_i2c_0_io_scl_writeEnable}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_i2c_0_io_sda_read}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_i2c_0_io_sda_read}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_i2c_0_io_sda_write}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_i2c_0_io_sda_write}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {system_i2c_0_io_sda_writeEnable}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {system_i2c_0_io_sda_writeEnable}]
set_input_delay -clock io_systemClk -max 5.958 [get_ports {system_spi_0_io_data_0_read}]
set_input_delay -clock io_systemClk -min 2.128 [get_ports {system_spi_0_io_data_0_read}]
set_output_delay -clock io_systemClk -max -3.903 [get_ports {system_spi_0_io_data_0_write}]
set_output_delay -clock io_systemClk -min -1.615 [get_ports {system_spi_0_io_data_0_write}]
set_output_delay -clock io_systemClk -max -3.913 [get_ports {system_spi_0_io_data_0_writeEnable}]
set_output_delay -clock io_systemClk -min -1.612 [get_ports {system_spi_0_io_data_0_writeEnable}]
set_input_delay -clock io_systemClk -max 5.958 [get_ports {system_spi_0_io_data_1_read}]
set_input_delay -clock io_systemClk -min 2.128 [get_ports {system_spi_0_io_data_1_read}]
set_output_delay -clock io_systemClk -max -3.903 [get_ports {system_spi_0_io_data_1_write}]
set_output_delay -clock io_systemClk -min -1.615 [get_ports {system_spi_0_io_data_1_write}]
set_output_delay -clock io_systemClk -max -3.913 [get_ports {system_spi_0_io_data_1_writeEnable}]
set_output_delay -clock io_systemClk -min -1.612 [get_ports {system_spi_0_io_data_1_writeEnable}]

# JTAG Constraints
####################
# create_clock -period <USER_PERIOD> [get_ports {jtag_inst1_TCK}]
# create_clock -period <USER_PERIOD> [get_ports {jtag_inst1_DRCK}]
set_output_delay -clock jtag_inst1_TCK -max 0.155 [get_ports {jtag_inst1_TDO}]
set_output_delay -clock jtag_inst1_TCK -min 0.053 [get_ports {jtag_inst1_TDO}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.374 [get_ports {jtag_inst1_CAPTURE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.134 [get_ports {jtag_inst1_CAPTURE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.374 [get_ports {jtag_inst1_RESET}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.134 [get_ports {jtag_inst1_RESET}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.374 [get_ports {jtag_inst1_RUNTEST}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.134 [get_ports {jtag_inst1_RUNTEST}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.323 [get_ports {jtag_inst1_SEL}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.116 [get_ports {jtag_inst1_SEL}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.374 [get_ports {jtag_inst1_UPDATE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.134 [get_ports {jtag_inst1_UPDATE}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -max 0.449 [get_ports {jtag_inst1_SHIFT}]
set_input_delay -clock_fall -clock jtag_inst1_TCK -min 0.161 [get_ports {jtag_inst1_SHIFT}]
